### ISSUE TITLE
[BUG] terraform import of citrixadc_vlan_channel_binding resource fails

### ISSUE THREAD

**Issue by HS1542** [citrix/terraform-provider-citrixadc#1053]
Output on terminal:

```
...
citrixadc_vlan_channel_binding.channel_bind_vlan913-2: Importing from ID "913"...
citrixadc_vlan_channel_binding.channel_bind_vlan913-2: Import prepared!
  Prepared citrixadc_vlan_channel_binding for import
citrixadc_vlan_channel_binding.channel_bind_vlan913-2: Refreshing state... [id=913]
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
 
 
Stack trace from the terraform-provider-citrixadc_v1.35.0 plugin:
 
panic: runtime error: index out of range [1] with length 1
 
goroutine 13 [running]:
github.com/citrix/terraform-provider-citrixadc/citrixadc.readVlan_channel_bindingFunc(0xc0010d3b20, {0x142f8a0?, 0xc0005c0740})
        github.com/citrix/terraform-provider-citrixadc/citrixadc/resource_citrixadc_vlan_channel_binding.go:86 +0x669
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc00074aaa0, 0xc00031c140, {0x142f8a0, 0xc0005c0740})
        [github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:470](mailto:github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:470) +0x1aa
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc00038e3a0, {0xc000386c60?, 0x5a7586?}, 0xc000386c60)
        [github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:535](mailto:github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:535) +0x34b
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler({0x15fe800?, 0xc00038e3a0}, {0x1b069c0, 0xc001257740}, 0xc0010d3650, 0x0)
        [github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3269](mailto:github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3269) +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000402000, {0x1b0a5e8, 0xc000800820}, 0xc00125ec60, 0xc0007f13e0, 0x239d590, 0x0)
        [google.golang.org/grpc@v1.52.0/server.go:1336](mailto:google.golang.org/grpc@v1.52.0/server.go:1336) +0xd13
google.golang.org/grpc.(*Server).handleStream(0xc000402000, {0x1b0a5e8, 0xc000800820}, 0xc00125ec60, 0x0)
        [google.golang.org/grpc@v1.52.0/server.go:1704](mailto:google.golang.org/grpc@v1.52.0/server.go:1704) +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        [google.golang.org/grpc@v1.52.0/server.go:965](mailto:google.golang.org/grpc@v1.52.0/server.go:965) +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        [google.golang.org/grpc@v1.52.0/server.go:963](mailto:google.golang.org/grpc@v1.52.0/server.go:963) +0x28a
 
Error: The terraform-provider-citrixadc_v1.35.0 plugin crashed!
 
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by rohit-myali** [comment]
Hi @HS1542,
In line 1, of the error, I can see that you are passing only `vlan_id` to the terraform import command, but you need to provide both `vlan_id` and `channel_id`, separated by a comma(",")

Link to the documentation: https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/vlan_channel_binding#import

So, for the above error the import line would be:
```
terraform import citrixadc_vlan_channel_binding.channel_bind_vlan913-2 913,<channel_id>
```

Replace <channel_id> in the above import line

**Comment by HS1542** [comment]
Thank you for your reply @rohit-myali.
Yes, absolutely, I must have been in a rush to not see that and was probably distracted by the output stating a bug :)
