### ISSUE TITLE
[BUG] - stack trace on import of dnsnsrec

### ISSUE THREAD

**Issue by adc-nerd** [citrix/terraform-provider-citrixadc#1078]
# Bug Report

**Describe the bug**
stack trace on import of built in nameserver records (dnsnsrec).

**To Reproduce**
Steps to reproduce the behaviour:
1. My terraform files are
```hcl
resource "citrixadc_dnsnsrec" "a_root_default" {
  nameserver = "a.root-servers.net"
  domain = "."
}
```
2. which terraform command I am getting the error
```cmd
terraform import citrixadc_dnsnsrec.a_root_default a.root-servers.net,.
```
3. Terraform output
```cmd
Error: Plugin did not respond
The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. 

Stack trace from the terraform-provider-citrixadc_v1.36.0.exe plugin:

panic: runtime error: index out of range [-1]

goroutine 123 [running]:
github.com/citrix/terraform-provider-citrixadc/citrixadc.readDnsnsrecFunc(0xc0003e8930, {0x11b3ac0?, 0xc0008ee440})
        github.com/citrix/terraform-provider-citrixadc/citrixadc/resource_citrixadc_dnsnsrec.go:102 +0x4fa
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc00066a960, 0xc000fa1810, {0x11b3ac0, 0xc0008ee440})
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:470 +0x1aa
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc000395a50, {0xc000071260?, 0x335266?}, 0xc000071260)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:535 +0x34b
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler({0x1382e40?, 0xc000395a50}, {0x188eea0, 0xc0007494d0}, 0xc0003e82a0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3269 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000005a0, {0x1892ac8, 0xc00034f040}, 0xc000b7f680, 0xc000345c80, 0x2129310, 0x0)
        google.golang.org/grpc@v1.52.0/server.go:1336 +0xd13
google.golang.org/grpc.(*Server).handleStream(0xc0000005a0, {0x1892ac8, 0xc00034f040}, 0xc000b7f680, 0x0)
        google.golang.org/grpc@v1.52.0/server.go:1704 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.52.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.52.0/server.go:963 +0x28a

Error: The terraform-provider-citrixadc_v1.36.0.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Expected behaviour**
Import and configuration of default/builtin nameserver records.

**Environment (please fill the following information):**
OS: Windows
Terraform: v1.5.5
citrixadc: v1.36.0

**Comment by rohit-myali** [comment]
Hello @adc-nerd ,
Thanks for contacting us. I did try to import `citrixadc_dnsnsrec` and it worked fine.
As I see from the documentation of [`citrixadc_dnsnsrec`](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/dnsnsrec#import), for the import command `domain` should be provided first then followed by a comma(,) and then `nameserver`.


As I see from the above terraform import command you provided, it should be modified. 
So, the terraform import  command for your configuration would be 
```bash
terraform import citrixadc_dnsnsrec.a_root_default .,a.root-servers.net
```

Please do try the above provided command and update us here.


Thank you
Rohit

**Comment by adc-nerd** [comment]
You are right. :innocent:

Is there a chance to intercept further stack traces with a simple error message like "domain not found" or "syntax error"?

**Comment by rohit-myali** [comment]
Thanks for the suggestion @adc-nerd, We will try to consider this in out next initiatives.
